# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage-core-system
  description: Core system for developer platform
spec:
  owner: group:default/platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  profile:
    displayName: Platform Engineering Team
    email: platform@example.com
  members:
    - user:guest
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-service
  description: Backstage Catalog Service Component
  tags:
    - core
    - service
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: sunghwan-joo/kt-backstage
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-team
  system: backstage-core-system

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: search-service
  description: Backstage Search Service Component
  tags:
    - core
    - service
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: sunghwan-joo/kt-backstage
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-team
  system: backstage-core-system

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs-service
  description: Backstage TechDocs Service Component
  tags:
    - core
    - documentation
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: sunghwan-joo/kt-backstage
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-team
  system: backstage-core-system

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scaffolder-templates
  description: Software Templates Service
  tags:
    - core
    - templates
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: sunghwan-joo/kt-backstage
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-team
  system: backstage-core-system