apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: ${{ values.repoName.owner }}/${{ values.repoName.repo }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest