apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | lower | replace(' ', '-') }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest