apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-actions-example
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest